services:

  mongodb:
    image: mongo:7
    container_name: google-keep-mongodb

    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongodb_data:/data/db

    networks:
      - keep-network

  backend:
    build: ./backend

    container_name: google-keep-backend

    restart: always

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      JWT_SECRET: your_secret_key
      MONGO_URI: mongodb://admin:password@mongodb:27017/googlekeep?authSource=admin

    depends_on:
      - mongodb

    networks:
      - keep-network

  frontend:
    build: ./frontend

    container_name: google-keep-frontend

    restart: always

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - keep-network

volumes:
  mongodb_data:

networks:
  keep-network:
